### ISSUE TITLE
Game keeps crashing when i try to open the setting menu

### ISSUE THREAD

**Issue by RegDuy** [minecraft-linux/mcpelauncher-manifest#103]
This issue only happens with the UI pack sea resource pack I don't know if its an issue with the pack or if its one with the launcher not working well with the pack cuz I get a zero code error

**Comment by Mhowser** [comment]
If you want some help you need to provide the crash log and the resource
pack (link to where you got the pack).
Use 0bin.net for the crash log.

**Comment by RegDuy** [comment]
here is the link to the pack it's a .mcpack so you may want to change it to a .zip before trying to open it

**Comment by Mhowser** [comment]
I can confirm this does crash when I try to go to settings.

https://0bin.net/paste/wNwvDpH7dui10Vix#XzCqa0Fc9kFHu38eFdFDhpBK9l9GCn+KHklPKUkL4O-

BTW, look at the comments on the pack website, nearly everyone has an issue with this pack causing a crash. And they are on regular mobile devices, which rules out the Linux launcher and client. 
The problem is the pack itself, so either wait for the pack makers to fix it themselves, or use a different pack in the meantime. May I suggest [Vanilla Deluxe: Core UI](http://www.mcbedrock.com/showthread.php?706). This pack makes the Bedrock Edition UI look just like Java Edition's!
