### ISSUE TITLE
"It seems that Minecraft has crashed Minecraft has exited with a non-zero error code."

### ISSUE THREAD

**Issue by M1L46R05** [minecraft-linux/mcpelauncher-manifest#288]
Unknown argument: -s
Process exited with unexpected exit code: 1

http://prnt.sc/s5kv3c

**Comment by ChristopherHX** [comment]
# You downloaded the wrong appimage
Do not use **ng.appimage** with the description
# THIS IS A TEST RELEASE OF THE NG BRANCH CURRENTLY NO SUPPORT FOR THIS APPIMAGE
in the description

**Comment by ScaryPit92** [comment]
calm down bro
okay , so how we can play minecraft bedrock edition without this appimage ?

**Comment by ChristopherHX** [comment]
Never mind, this is now fixed in ng.
Pixelscale was ignored in my fork (kept this cli switch) and removed in ng (without my knowledge).
The mcpelauncher-ui-qt@ng got updated to fix this issue. (The -s switch will not be back anytime soon)

My stable AppImage can be found here https://github.com/ChristopherHX/linux-packaging-scripts/releases/tag/appimage

Sorry I have confused a lot of peoply by providing the stable, behind the experimental appimage.
I know everyone may linked to this download page, saw the first and thought this launcher is still a Test Release and no stable would exist.
