### ISSUE TITLE
code 127

### ISSUE THREAD

**Issue by khangtheky22** [minecraft-linux/mcpelauncher-manifest#329]
/usr/bin/mcpelauncher-client: error while loading shared libraries: libEGL.so.1: cannot open shared object file: No such file or directory
Process exited with unexpected exit code: 127

**Comment by ChristopherHX** [comment]
You are using the unsupported release from the wiki?
It would be worth installing the debian dependencies like written here https://github.com/ChristopherHX/linux-packaging-scripts/releases/tag/appimage

Because my appimages now tell you to read the page to fix it yourself.
**Using the wiki version you cannot run latest 1.14.60.5, only 1.14.1.5**

**Comment by ChristopherHX** [comment]
Stale issue
