### ISSUE TITLE
Hope you can fix it so i can run Catalina MacOS 10.15 also got this error

### ISSUE THREAD

**Issue by randeum** [minecraft-linux/mcpelauncher-manifest#346]
Minecraft (x86):
  Supported on your Device? No
  Game Installed? Yes
  Launcher Installed? Yes
Minecraft (armeabi-v7a):
  Supported on your Device? N/A
  Game Installed? No
  Launcher Installed? No
Minecraft (arm64-v8a):
  Supported on your Device? N/A
  Game Installed? No
  Launcher Installed? No
Minecraft (x86_64):
  Supported on your Device? N/A
  Game Installed? No
  Launcher Installed? No

**Comment by ChristopherHX** [comment]
The userinterface is just to buggy to tell you to move to ng:
Please replace the installed launcher with
**PLEASE READ IT'S DESCRIPTION CAREFULLY**
https://github.com/ChristopherHX/osx-packaging-scripts/releases/tag/ng.dmg

Stable 10.10-10.14 is 100% incompatible with "Catalina MacOS 10.15"

More details about the error message:
You have installed Minecraft (x86) while x86 support was removed by apply since 10.15
Supported on your Device? No (Because catalina cannot run 32bit) so not usable
Game Installed? Yes (the specfic game version is launchable on older macOS and linux)
Launcher Installed? Yes (32bit launcher installed, but not usable on 10.15+)

You need
Minecraft (x86_64):
Supported on your Device? N/A (means you need the ng launcher linked above (the experimenal one without 10.10 - 10.14)
Game Installed? No (You will need to delete the old version and install a x86_64 one)
Launcher Installed? No (means you need the ng launcher linked above (the experimenal one without 10.10 - 10.14)

~~I'm so sad, because a lot of people don't read the desciption and install 10.10 - 10.14 software on 10.15~~

**Comment by ChristopherHX** [comment]
Stale issue
