### ISSUE TITLE
Cannot Load this world

### ISSUE THREAD

**Issue by orangemn6** [minecraft-linux/mcpelauncher-manifest#422]
Whenever I try to go in my world it says cannot load this world

**Comment by ChristopherHX** [comment]
Please check Minecraft Profile Settings
This will happen if you have selected Application storage in appimage or dmg release,
not the default for this Launcher
This screenshoot shows a invalid setting of this launcher e.g. your bug 
![Screenshot_20201104-154050](https://user-images.githubusercontent.com/44845461/98125450-ca2faa00-1eb4-11eb-9aa3-3dcf9dfc1c5c.png)
please change it to external, until internal storage works again
![Screenshot_20201104-154134](https://user-images.githubusercontent.com/44845461/98125464-cef45e00-1eb4-11eb-8323-9a3d2c3c86ac.png)
![Screenshot_20201104-154146](https://user-images.githubusercontent.com/44845461/98125482-d582d580-1eb4-11eb-898d-abca83e68f4b.png)

Otherwise I would need more information like
- Launcher Version
- Where do you get this Launcher Version
- gamelog, enable it with "show gamelog" Launcher settings, gear button

to find the real error

**Comment by orangemn6** [comment]
it works!! thank you so much!! btw i didnt pirate the apk
