### ISSUE TITLE
Crash instantly after clicking "Play", regardless of version selected.

### ISSUE THREAD

**Issue by Maccraft123** [minecraft-linux/mcpelauncher-manifest#459]
I can't get anything to work, I am using self-compiled Mesa version installed at /opt/lib/arm-linux-gnueabihf/dri for armhf and /opt/lib/aarch64-linux-gnu/dri for aarch64 binaries.
I am using aarch64 Debian on MT8183 laptop, XWayland is working correctly and all dependencies are installed.
I have tried updating Appimage and Minecraft versions.
Issue isn't helped by changing version between 1.16 and 1.14.
Screenshot of game logs:
![20210211_12h56m16s_grim](https://user-images.githubusercontent.com/47303937/107633578-8ba24c00-6c68-11eb-96e5-5f63b1cc567c.png)

Logs:
[logs.txt](https://github.com/minecraft-linux/mcpelauncher-manifest/files/5965015/logs.txt)

**Comment by ChristopherHX** [comment]
Your crash is the result not beeing able to load your selfbuild mesa drivers, because of missing `libz.so` or a collision with [this arm32/arm64 AppImage script](https://github.com/ChristopherHX/linux-packaging-scripts/blob/feature-jnivm/AppRun)

I'm not actively testing the arm versions of this launcher, but it used to work with system mesa of ubuntu20.04 arm64 on a low power Raspberry Pi 3 and 4. Additionally I have been able (last year) to use my own build of older mesa drivers on arm32.

> Issue isn't helped by changing version between 1.16 and 1.14.

That point doesn't matter, because it (the `mcpelauncher-client`) cannot load your selfbuild driver.

Why does your mediatek driver need `libz.so`?
- On debian it should try to load `libz.so.1` instead
- Try add the folder of `libz.so` to `LD_LIBRARY_PATH`.
  - `LD_LIBRARY_PATH=/path/to/folder/of/libz <pathtoappimage>.AppImage`
  - Build the sw_rast driver to load the game with poor performance
- Otherwise try Compile the launcher yourself with cmake, clang, qt5
  - wiki is outdated
  - make shure to change the branch to `ng`, updated git submodules, this repo contains the mainproject of the launcher
  - You might find [here](https://github.com/ChristopherHX/Buildbot/blob/16ea97ad8892ac9e88492089a0513c8c5662cd57/.github/workflows/manual.yml) something about compiling / dependencies for debian / ubuntu
  - `CC=clang CXX=clang++ cmake ..`
  - `make`
  - `sudo make install`
    - launch it directly via `mcpelauncher-client`
    - Check your gpu driver with `mcpelauncher-client -v`
 - [Also available on flathub, but is unlikly to be able to use your custom drivers either](https://flathub.org/apps/details/io.mrarm.mcpelauncher)
   - This runs within the flatpak sandbox and is bigger than the AppImage

**Comment by Maccraft123** [comment]
WIth 32bit libz.so in LD_LIBRARY_PATH i am now able to run 32bit GL applications. It looks like mesa wants to have libz for whatever reason
And now It just exits with code 11 with no explanation in logs on screen or in terminal

**Comment by Maccraft123** [comment]
It seems like it failed to auto-update for whatever reason.
One manual update later it works \o/
