### ISSUE TITLE
Corrupted Version of Minecraft

### ISSUE THREAD

**Issue by GabeCoder** [minecraft-linux/mcpelauncher-manifest#471]
**CORRUPTED**
I like to play the latest versions of Minecraft to ensure the best stable and playable experience both singleplayer and multiplayer. The problem with the latest version, however, is that it is both corrupted and unplayable. I just want to point this out to the developers of this launcher so it can be fixed.

Information about version:
I run the Linux version of the launcher on a 64-bit distro.
The version I am trying to run is 1.16.210 (The Nether Update 2021).
I don’t prefer Google Play. (Google Play is unstable, however I have installed this version to legally acquire Minecraft.)

Just pointing this out to make sure that you all are aware.

**Comment by GabeCoder** [comment]
**Update:** My friend can’t play Minecraft with me since the version I am running is outdated. Can you fix the incompatible version of Minecraft?

My system updates every time it boots up.

**Comment by derpyegplant** [comment]
I also cant play the newest version. I host a world that me and my friends play and I cant open it for them. Pls fix this soon

**Comment by derpyegplant** [comment]
Update: Here is the log, it says something about the game libraries. 

21:56:42 Info  [Launcher] Version: client 2a16784 / manifest 592d02d
21:56:42 Info  [Launcher] CPU: GenuineIntel Intel(R) Core(TM) i3-1005G1 CPU @ 1.20GHz
21:56:42 Info  [Launcher] CPU supports SSSE3: YES
21:56:42 Trace [Launcher] Loading hybris libraries
21:56:42 Trace [HybrisUtils] Loaded OS library libm.so.6
21:56:42 Trace [HybrisUtils] Loaded OS library libz.so.1
21:56:42 Trace [HybrisUtils] Loaded OS library /app/share/mcpelauncher/lib/native/x86_64/libfmod.so.12.0
load_library: Undefined symbol glMultMatrixf
load_library: Undefined symbol glFogfv
load_library: Undefined symbol glNormalPointer
load_library: Undefined symbol glVertexPointer
load_library: Undefined symbol glLightfv
load_library: Undefined symbol glLoadIdentity
load_library: Undefined symbol glRotatef
load_library: Undefined symbol glMatrixMode
load_library: Undefined symbol glPopMatrix
load_library: Undefined symbol glTranslatef
load_library: Undefined symbol glOrthof
load_library: Undefined symbol glPushMatrix
load_library: Undefined symbol glEnableClientState
load_library: Undefined symbol glShadeModel
load_library: Undefined symbol glViewport
load_library: Undefined symbol glVertexAttrib2fv
load_library: Undefined symbol glVertexAttrib1fv
load_library: Undefined symbol glValidateProgram
load_library: Undefined symbol glUniformMatrix4fv
load_library: Undefined symbol glUniform4iv
load_library: Undefined symbol glVertexAttrib1f
load_library: Undefined symbol glUniform4fv
load_library: Undefined symbol glUniform4f
load_library: Undefined symbol glUniform3i
load_library: Undefined symbol glAlphaFunc
load_library: Undefined symbol glUniform3fv
load_library: Undefined symbol glUniform2i
load_library: Undefined symbol glScalef
load_library: Undefined symbol glUniform4i
load_library: Undefined symbol glUniform2fv
load_library: Undefined symbol glUniform2f
load_library: Undefined symbol glVertexAttribPointer
load_library: Undefined symbol glUniform1iv
load_library: Undefined symbol glUniform1i
load_library: Undefined symbol glUniform1fv
load_library: Undefined symbol glUniform1f
load_library: Undefined symbol glTexParameteriv
load_library: Undefined symbol glStencilOpSeparate
load_library: Undefined symbol glStencilMaskSeparate
load_library: Undefined symbol glStencilMask
load_library: Undefined symbol glStencilFuncSeparate
load_library: Undefined symbol glFramebufferRenderbuffer
load_library: Undefined symbol glEnable
load_library: Undefined symbol glTexParameteri
load_library: Undefined symbol glBufferSubData
load_library: Undefined symbol glDrawArrays
load_library: Undefined symbol glGetRenderbufferParameteriv
load_library: Undefined symbol glDetachShader
load_library: Undefined symbol glDeleteFramebuffers
load_library: Undefined symbol glDrawElements
load_library: Undefined symbol glDeleteProgram
load_library: Undefined symbol glDepthRangef
load_library: Undefined symbol glCullFace
load_library: Undefined symbol glCreateProgram
load_library: Undefined symbol glDisableVertexAttribArray
load_library: Undefined symbol glColorPointer
load_library: Undefined symbol glDeleteRenderbuffers
load_library: Undefined symbol glPixelStorei
load_library: Undefined symbol glDeleteShader
load_library: Undefined symbol glGetProgramInfoLog
load_library: Undefined symbol glColor4f
load_library: Undefined symbol glUseProgram
load_library: Undefined symbol glClearStencil
load_library: Undefined symbol glShaderBinary
load_library: Undefined symbol glIsShader
load_library: Undefined symbol glReleaseShaderCompiler
load_library: Undefined symbol glBlendEquation
load_library: Undefined symbol glShaderSource
load_library: Undefined symbol glGetVertexAttribPointerv
load_library: Undefined symbol glDepthMask
load_library: Undefined symbol glFogf
load_library: Undefined symbol glVertexAttrib3f
load_library: Undefined symbol glUniformMatrix3fv
load_library: Undefined symbol glGetShaderInfoLog
load_library: Undefined symbol glActiveTexture
load_library: Undefined symbol glTexParameterfv
load_library: Undefined symbol glCopyTexImage2D
load_library: Undefined symbol glStencilOp
load_library: Undefined symbol glClear
load_library: Undefined symbol glIsBuffer
load_library: Undefined symbol glGetBufferParameteriv
load_library: Undefined symbol glDisable
load_library: Undefined symbol glBlendFunc
load_library: Undefined symbol glBlendEquationSeparate
load_library: Undefined symbol glFinish
load_library: Undefined symbol glUniformMatrix2fv
load_library: Undefined symbol glIsTexture
load_library: Undefined symbol glTexSubImage2D
load_library: Undefined symbol glBindFramebuffer
load_library: Undefined symbol glBlendColor
load_library: Undefined symbol glGetUniformLocation
load_library: Undefined symbol glBindBuffer
load_library: Undefined symbol glBlendFuncSeparate
load_library: Undefined symbol glBindTexture
load_library: Undefined symbol glVertexAttrib2f
load_library: Undefined symbol glBindRenderbuffer
load_library: Undefined symbol glUniform3iv
load_library: Undefined symbol glGetVertexAttribiv
load_library: Undefined symbol glDeleteTextures
load_library: Undefined symbol glFlush
load_library: Undefined symbol glClearColor
load_library: Undefined symbol glDeleteBuffers
load_library: Undefined symbol glCreateShader
load_library: Undefined symbol glDepthFunc
load_library: Undefined symbol glGetString
load_library: Undefined symbol glAttachShader
load_library: Undefined symbol glCopyTexSubImage2D
load_library: Undefined symbol glClearDepthf
load_library: Undefined symbol glVertexAttrib3fv
load_library: Undefined symbol glTexParameterf
load_library: Undefined symbol glGetAttribLocation
load_library: Undefined symbol glTexImage2D
load_library: Undefined symbol glLinkProgram
load_library: Undefined symbol glCheckFramebufferStatus
load_library: Undefined symbol glUniform2iv
load_library: Undefined symbol glColorMask
load_library: Undefined symbol glCompileShader
load_library: Undefined symbol glSampleCoverage
load_library: Undefined symbol glEnableVertexAttribArray
load_library: Undefined symbol glCompressedTexSubImage2D
load_library: Undefined symbol glUniform3f
load_library: Undefined symbol glGetTexParameteriv
load_library: Undefined symbol glFramebufferTexture2D
load_library: Undefined symbol glFrontFace
load_library: Undefined symbol glVertexAttrib4fv
load_library: Undefined symbol glGenBuffers
load_library: Undefined symbol glCompressedTexImage2D
load_library: Undefined symbol glGetFloatv
load_library: Undefined symbol glGenFramebuffers
load_library: Undefined symbol glBindAttribLocation
load_library: Undefined symbol glGenRenderbuffers
load_library: Undefined symbol glGenTextures
load_library: Undefined symbol glBufferData
load_library: Undefined symbol glHint
load_library: Undefined symbol glFogx
load_library: Undefined symbol glDisableClientState
load_library: Undefined symbol glGetActiveAttrib
load_library: Undefined symbol glIsRenderbuffer
load_library: Undefined symbol glGenerateMipmap
load_library: Undefined symbol glGetAttachedShaders
load_library: Undefined symbol glGetBooleanv
load_library: Undefined symbol glGetError
load_library: Undefined symbol glVertexAttrib4f
load_library: Undefined symbol glGetProgramiv
load_library: Undefined symbol glGetUniformfv
load_library: Undefined symbol glIsFramebuffer
load_library: Undefined symbol glTexCoordPointer
load_library: Undefined symbol glGetFramebufferAttachmentParameteriv
load_library: Undefined symbol glGetShaderiv
load_library: Undefined symbol glGetIntegerv
load_library: Undefined symbol glGetShaderPrecisionFormat
load_library: Undefined symbol glGetShaderSource
load_library: Undefined symbol glGetUniformiv
load_library: Undefined symbol glGetTexParameterfv
load_library: Undefined symbol glReadPixels
load_library: Undefined symbol glLightModelf
load_library: Undefined symbol glGetVertexAttribfv
load_library: Undefined symbol glIsEnabled
load_library: Undefined symbol glStencilFunc
load_library: Undefined symbol glIsProgram
load_library: Undefined symbol glLineWidth
load_library: Undefined symbol glScissor
load_library: Undefined symbol glGetActiveUniform
load_library: Undefined symbol glPolygonOffset
load_library: Undefined symbol glRenderbufferStorage
21:56:42 Trace [Launcher] Loading Minecraft library
21:56:42 Error [MinecraftUtils] Failed to load Minecraft: dlopen failed: cannot locate symbol "malloc_usable_size" referenced by "/home/compoot/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.16.210.05/lib/x86_64/libminecraftpe.so"...
21:56:42 Error [Launcher] Failed to load Minecraft library, please reinstall or wait for an update to support the new release

Incompatible Minecraft installation, please select a different or older Version
This Launcher is a free Open Source Software which usually fell behind official updates from Google Play
In some cases there are missing game files,
missing Symbols expected to be provided by this Launcher via updates
 or otherwise broke the Launcher

**Comment by GabeCoder** [comment]
> Update: Here is the log, it says something about the game libraries.
> 
> 21:56:42 Info [Launcher] Version: client 2a16784 / manifest [592d02d](https://github.com/minecraft-linux/mcpelauncher-manifest/commit/592d02d8f82b5abf0769ee6fc0ebbd7ae6bb5926)
> 21:56:42 Info [Launcher] CPU: GenuineIntel Intel(R) Core(TM) i3-1005G1 CPU @ 1.20GHz
> 21:56:42 Info [Launcher] CPU supports SSSE3: YES
> 21:56:42 Trace [Launcher] Loading hybris libraries
> 21:56:42 Trace [HybrisUtils] Loaded OS library libm.so.6
> 21:56:42 Trace [HybrisUtils] Loaded OS library libz.so.1
> 21:56:42 Trace [HybrisUtils] Loaded OS library /app/share/mcpelauncher/lib/native/x86_64/libfmod.so.12.0
> load_library: Undefined symbol glMultMatrixf
> load_library: Undefined symbol glFogfv
> load_library: Undefined symbol glNormalPointer
> load_library: Undefined symbol glVertexPointer
> load_library: Undefined symbol glLightfv
> load_library: Undefined symbol glLoadIdentity
> load_library: Undefined symbol glRotatef
> load_library: Undefined symbol glMatrixMode
> load_library: Undefined symbol glPopMatrix
> load_library: Undefined symbol glTranslatef
> load_library: Undefined symbol glOrthof
> load_library: Undefined symbol glPushMatrix
> load_library: Undefined symbol glEnableClientState
> load_library: Undefined symbol glShadeModel
> load_library: Undefined symbol glViewport
> load_library: Undefined symbol glVertexAttrib2fv
> load_library: Undefined symbol glVertexAttrib1fv
> load_library: Undefined symbol glValidateProgram
> load_library: Undefined symbol glUniformMatrix4fv
> load_library: Undefined symbol glUniform4iv
> load_library: Undefined symbol glVertexAttrib1f
> load_library: Undefined symbol glUniform4fv
> load_library: Undefined symbol glUniform4f
> load_library: Undefined symbol glUniform3i
> load_library: Undefined symbol glAlphaFunc
> load_library: Undefined symbol glUniform3fv
> load_library: Undefined symbol glUniform2i
> load_library: Undefined symbol glScalef
> load_library: Undefined symbol glUniform4i
> load_library: Undefined symbol glUniform2fv
> load_library: Undefined symbol glUniform2f
> load_library: Undefined symbol glVertexAttribPointer
> load_library: Undefined symbol glUniform1iv
> load_library: Undefined symbol glUniform1i
> load_library: Undefined symbol glUniform1fv
> load_library: Undefined symbol glUniform1f
> load_library: Undefined symbol glTexParameteriv
> load_library: Undefined symbol glStencilOpSeparate
> load_library: Undefined symbol glStencilMaskSeparate
> load_library: Undefined symbol glStencilMask
> load_library: Undefined symbol glStencilFuncSeparate
> load_library: Undefined symbol glFramebufferRenderbuffer
> load_library: Undefined symbol glEnable
> load_library: Undefined symbol glTexParameteri
> load_library: Undefined symbol glBufferSubData
> load_library: Undefined symbol glDrawArrays
> load_library: Undefined symbol glGetRenderbufferParameteriv
> load_library: Undefined symbol glDetachShader
> load_library: Undefined symbol glDeleteFramebuffers
> load_library: Undefined symbol glDrawElements
> load_library: Undefined symbol glDeleteProgram
> load_library: Undefined symbol glDepthRangef
> load_library: Undefined symbol glCullFace
> load_library: Undefined symbol glCreateProgram
> load_library: Undefined symbol glDisableVertexAttribArray
> load_library: Undefined symbol glColorPointer
> load_library: Undefined symbol glDeleteRenderbuffers
> load_library: Undefined symbol glPixelStorei
> load_library: Undefined symbol glDeleteShader
> load_library: Undefined symbol glGetProgramInfoLog
> load_library: Undefined symbol glColor4f
> load_library: Undefined symbol glUseProgram
> load_library: Undefined symbol glClearStencil
> load_library: Undefined symbol glShaderBinary
> load_library: Undefined symbol glIsShader
> load_library: Undefined symbol glReleaseShaderCompiler
> load_library: Undefined symbol glBlendEquation
> load_library: Undefined symbol glShaderSource
> load_library: Undefined symbol glGetVertexAttribPointerv
> load_library: Undefined symbol glDepthMask
> load_library: Undefined symbol glFogf
> load_library: Undefined symbol glVertexAttrib3f
> load_library: Undefined symbol glUniformMatrix3fv
> load_library: Undefined symbol glGetShaderInfoLog
> load_library: Undefined symbol glActiveTexture
> load_library: Undefined symbol glTexParameterfv
> load_library: Undefined symbol glCopyTexImage2D
> load_library: Undefined symbol glStencilOp
> load_library: Undefined symbol glClear
> load_library: Undefined symbol glIsBuffer
> load_library: Undefined symbol glGetBufferParameteriv
> load_library: Undefined symbol glDisable
> load_library: Undefined symbol glBlendFunc
> load_library: Undefined symbol glBlendEquationSeparate
> load_library: Undefined symbol glFinish
> load_library: Undefined symbol glUniformMatrix2fv
> load_library: Undefined symbol glIsTexture
> load_library: Undefined symbol glTexSubImage2D
> load_library: Undefined symbol glBindFramebuffer
> load_library: Undefined symbol glBlendColor
> load_library: Undefined symbol glGetUniformLocation
> load_library: Undefined symbol glBindBuffer
> load_library: Undefined symbol glBlendFuncSeparate
> load_library: Undefined symbol glBindTexture
> load_library: Undefined symbol glVertexAttrib2f
> load_library: Undefined symbol glBindRenderbuffer
> load_library: Undefined symbol glUniform3iv
> load_library: Undefined symbol glGetVertexAttribiv
> load_library: Undefined symbol glDeleteTextures
> load_library: Undefined symbol glFlush
> load_library: Undefined symbol glClearColor
> load_library: Undefined symbol glDeleteBuffers
> load_library: Undefined symbol glCreateShader
> load_library: Undefined symbol glDepthFunc
> load_library: Undefined symbol glGetString
> load_library: Undefined symbol glAttachShader
> load_library: Undefined symbol glCopyTexSubImage2D
> load_library: Undefined symbol glClearDepthf
> load_library: Undefined symbol glVertexAttrib3fv
> load_library: Undefined symbol glTexParameterf
> load_library: Undefined symbol glGetAttribLocation
> load_library: Undefined symbol glTexImage2D
> load_library: Undefined symbol glLinkProgram
> load_library: Undefined symbol glCheckFramebufferStatus
> load_library: Undefined symbol glUniform2iv
> load_library: Undefined symbol glColorMask
> load_library: Undefined symbol glCompileShader
> load_library: Undefined symbol glSampleCoverage
> load_library: Undefined symbol glEnableVertexAttribArray
> load_library: Undefined symbol glCompressedTexSubImage2D
> load_library: Undefined symbol glUniform3f
> load_library: Undefined symbol glGetTexParameteriv
> load_library: Undefined symbol glFramebufferTexture2D
> load_library: Undefined symbol glFrontFace
> load_library: Undefined symbol glVertexAttrib4fv
> load_library: Undefined symbol glGenBuffers
> load_library: Undefined symbol glCompressedTexImage2D
> load_library: Undefined symbol glGetFloatv
> load_library: Undefined symbol glGenFramebuffers
> load_library: Undefined symbol glBindAttribLocation
> load_library: Undefined symbol glGenRenderbuffers
> load_library: Undefined symbol glGenTextures
> load_library: Undefined symbol glBufferData
> load_library: Undefined symbol glHint
> load_library: Undefined symbol glFogx
> load_library: Undefined symbol glDisableClientState
> load_library: Undefined symbol glGetActiveAttrib
> load_library: Undefined symbol glIsRenderbuffer
> load_library: Undefined symbol glGenerateMipmap
> load_library: Undefined symbol glGetAttachedShaders
> load_library: Undefined symbol glGetBooleanv
> load_library: Undefined symbol glGetError
> load_library: Undefined symbol glVertexAttrib4f
> load_library: Undefined symbol glGetProgramiv
> load_library: Undefined symbol glGetUniformfv
> load_library: Undefined symbol glIsFramebuffer
> load_library: Undefined symbol glTexCoordPointer
> load_library: Undefined symbol glGetFramebufferAttachmentParameteriv
> load_library: Undefined symbol glGetShaderiv
> load_library: Undefined symbol glGetIntegerv
> load_library: Undefined symbol glGetShaderPrecisionFormat
> load_library: Undefined symbol glGetShaderSource
> load_library: Undefined symbol glGetUniformiv
> load_library: Undefined symbol glGetTexParameterfv
> load_library: Undefined symbol glReadPixels
> load_library: Undefined symbol glLightModelf
> load_library: Undefined symbol glGetVertexAttribfv
> load_library: Undefined symbol glIsEnabled
> load_library: Undefined symbol glStencilFunc
> load_library: Undefined symbol glIsProgram
> load_library: Undefined symbol glLineWidth
> load_library: Undefined symbol glScissor
> load_library: Undefined symbol glGetActiveUniform
> load_library: Undefined symbol glPolygonOffset
> load_library: Undefined symbol glRenderbufferStorage
> 21:56:42 Trace [Launcher] Loading Minecraft library
> 21:56:42 Error [MinecraftUtils] Failed to load Minecraft: dlopen failed: cannot locate symbol "malloc_usable_size" referenced by "/home/compoot/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.16.210.05/lib/x86_64/libminecraftpe.so"...
> 21:56:42 Error [Launcher] Failed to load Minecraft library, please reinstall or wait for an update to support the new release
> 
> Incompatible Minecraft installation, please select a different or older Version
> This Launcher is a free Open Source Software which usually fell behind official updates from Google Play
> In some cases there are missing game files,
> missing Symbols expected to be provided by this Launcher via updates
> or otherwise broke the Launcher

Yeah, it seems that everyone has the same problem.
Hey, how come my CPU is about 1.5 to 2 Gigahertz?

**Comment by GabeCoder** [comment]
How long do you developers expect for the corruption issue to be resolved, as this problem has lasted for 2 days and counting already.

My friends are currently unable to play with me on the computer.

**Comment by cmt29** [comment]
Hey GabeTheCoder, I hope you don't mind my saying so, but I'd recommend
some patience, and dare I say a bit more politeness, here. The generous
developers who've made this launcher aren't paid for doing it as far as I'm
aware, and they probably have loads of other more important
responsibilities.

I know it's frustrating to have to wait, but it's not that big a problem in
the whole grand scheme of things.

**Comment by GabeCoder** [comment]
> Hey GabeTheCoder, I hope you don't mind my saying so, but I'd recommend some patience, and dare I say a bit more politeness, here. The generous developers who've made this launcher aren't paid for doing it as far as I'm aware, and they probably have loads of other more important responsibilities. I know it's frustrating to have to wait, but it's not that big a problem in the whole grand scheme of things.
> […](#)

Don’t worry. Time won’t be an issue.

**Comment by GabeCoder** [comment]
I wish I had a PayPal account to pay y’all $7.50. I’m not yet allowed to do that though. I think I need to be 18 or 21?

**Comment by GabeCoder** [comment]
Right now, I am busy crafting a meat factory with some redstone.

**Comment by GabeCoder** [comment]
According to a comment on another player’s issue related to this, the version has become very unstable that the game is deteriorated. I’m not planting a currently ticking time bomb for this, but I’m only pointing these problems out for tips on how to fix this version.

Good luck!

**Comment by GabeCoder** [comment]
I also just realized that block lag has been fixed in that version. Cool.

This is not a time bomb.

**Comment by donfb** [comment]
I can confirm my girlfriend is having the exact same issue

**Comment by GabeCoder** [comment]
...
Piglins just attacked me. Great.

**Comment by GabeCoder** [comment]
Day 6: I started rearranging my Nether spawn until piglins decided to be jerks and attack me. I definitely will need a friend to destroy that portal in the Nether to get a better spawn.

**Comment by GabeCoder** [comment]
Although every Linux user is experiencing the exact same problem, I will give you information about my software and hardware.

Operating System: Raspberry Pi OS (64-bit)
CPU: 2GhZ ARM
RAM: 2GB
SD: 32GB
Additional Hardware: Heatsink, 5V Fan

Even with a 2GhZ CPU and RAM with 2GB, it is still enough to run the title screen at 160 FPS.
I’ll update you with an error log ASAP.

**Comment by GabeCoder** [comment]
Here is the error log that displays the corruption information for Minecraft 1.16.210.05.

```
21:44:19 Info  [Launcher] Version: client 2a16784 / manifest 592d02d
21:44:19 Trace [Launcher] Loading hybris libraries
21:44:19 Trace [HybrisUtils] Loaded OS library libz.so.1
21:44:19 Warn  [FMOD] Failed to load host libfmod: 'Failed to find data file: lib/native/armeabi-v7a/libfmod.so.10.20', use experimental pulseaudio backend if available
21:44:19 Trace [Launcher] Loading Minecraft library
21:44:19 Error [MinecraftUtils] Failed to load Minecraft: dlopen failed: cannot locate symbol "malloc_usable_size" referenced by "/home/pi/.local/share/mcpelauncher/versions/1.16.210.05/lib/armeabi-v7a/libminecraftpe.so"...
21:44:19 Error [Launcher] Failed to load Minecraft library, please reinstall or wait for an update to support the new release

Incompatible Minecraft installation, please select a different or older Version
This Launcher is a free Open Source Software which usually fell behind official updates from Google Play
In some cases there are missing game files,
missing Symbols expected to be provided by this Launcher via updates
 or otherwise broke the Launcher
```

**Comment by GabeCoder** [comment]
I have some clues and questions.
There are two errors displayed in the log, one of them involving an extraterrestrial symbol from the updated version, and the other failing to load the Minecraft library.
Since the symbols are missing from the game, they may be the reason why the game is corrupted and can’t safely run. You may also want to focus on the game library to see if it is also causing incompatibility.

The question I am asking is, are Mac users affected by this corruption, or can they run Minecraft without issues? Most of these problems seem to involve Linux operating systems.

**Comment by edam** [comment]
Duplicate of #470

**Comment by GabeCoder** [comment]
> Duplicate of #470

Understandable.

**Comment by GabeCoder** [comment]
Although I am currently commenting on a duplicate, I was just asking how you all are doing on the bug squash, since I heard that progress is being made. Good work!

This is not a time bomb.

**Comment by GabeCoder** [comment]
Minecraft Bedrock 1.16.210 is finally out! It’s time to update our launchers and get in the game!
