### ISSUE TITLE
AppImage not launching on raspberry pi 3B+ running raspberrypi os 32 bit...

### ISSUE THREAD

**Issue by Haus3master** [minecraft-linux/mcpelauncher-manifest#476]
This is what comes out as output:
pi@raspberrypi:~ $ ./MC.AppImage 
/tmp/.mount_MC.AppXnn8l2/usr/bin/mcpelauncher-ui-qt: line 10: /tmp/.mount_MC.AppXnn8l2/usr/bin/usr/bin/msa-daemon: No such file or directory
/tmp/.mount_MC.AppXnn8l2/usr/bin/mcpelauncher-ui-qt: line 14: /tmp/.mount_MC.AppXnn8l2/usr/bin/usr/bin/mcpelauncher-ui-qt: No such file or directory
/tmp/.mount_MC.AppXnn8l2/usr/bin/mcpelauncher-ui-qt: line 12: /tmp/.mount_MC.AppXnn8l2/usr/bin/usr/bin/msa-ui-qt: No such file or directory
/tmp/.mount_MC.AppXnn8l2/usr/bin/mcpelauncher-ui-qt: line 15: kill: (851) - No such process
/tmp/.mount_MC.AppXnn8l2/usr/bin/mcpelauncher-ui-qt: line 16: kill: (850) - No such process
pi@raspberrypi:~ $

**Comment by ChristopherHX** [comment]
Wow, the appimage tool fooled me..., but it's to early for 1.4.2021...

**Comment by ChristopherHX** [comment]
Should be fixed now.
https://github.com/ChristopherHX/linux-packaging-scripts/commit/c4faf27d030b8ed3824b0a928fc0c96c91560c04

This was a copy paste bug, caused by me...

**Comment by ChristopherHX** [comment]
This bug should be fixed with https://github.com/ChristopherHX/linux-packaging-scripts/releases/tag/v0.1-beta-21-652

Steps to fix the issue
```
cp ./MC.AppImage.zs-old ./MC.AppImage
./MC.AppImage
```
Then update the AppImage again to install the hotfix.

**Comment by Haus3master** [comment]
The latest one works great so far... I have noticed that, 1.16.210.05 isn't loading the marketplace and, also, the achievements crash the game...
I'm not asking/forcing for a fix, but, I just want to know what their status is as of now...
Also, don't fix the achievements as of now, since, there are many rumours about new ui being added, if the new ui is actually added, then it will be a bit convenient for you

**Comment by ChristopherHX** [comment]
> I just want to know what their status is as of now

I'm only working on critical issues, updates normally all 4 month (Except some one fix the issue and open a PR before I would normally publish a new Release)
Like:
- New Game Release crashs on open for all users
- Launcher doesn't open at all
- Some Launcher functionality stops working like Xbox login
- Mouse capture not working

New versions are tracked in this issue https://github.com/ChristopherHX/mcpelauncher-manifest/issues/48.

Achievements aren't critical, because you can just open xbox.com to see them.
By the way the reason why it crashs is a endless recursion while navigating to the Achievements page.

**Comment by Haus3master** [comment]
Thanks for the info!

**Comment by Haus3master** [comment]
This issue was fixed with a release, and hence, in going to choose this issue for now...
