### ISSUE TITLE
Latest beta (1.17.30.23) is unsupported

### ISSUE THREAD

**Issue by kyleplo** [minecraft-linux/mcpelauncher-manifest#591]
When I try to run the latest Minecraft Bedrock beta (1.17.30.23), I get the following error:
```
Your previously downloaded Minecraft Version might be unsupported or just corrupted.
if you wanted to play a Beta or a new Release please wait patiently for an update,
please choose a compatible version from the profile Editor
otherwise if you have updated the Launcher recently.
e.g. a crash please delete it in Settings,
then download it again via the updated Launcher.
```
I am able to load other Minecraft Bedrock versions with this launcher, so I believe the issue is related to this particular beta, which made some major changes.
Platform: MacOS Big Sur (Intel)

**Comment by ChristopherHX** [comment]
You know mojang reverted the change in 1.17.30.24 and moved it to 1.17.40.20. It will take some month till you require an update.
I won't publish (at least not within 12 month) the source code of the Patches for this game versions, because of ongoing pirarcy with this launcher's source code. Only members of https://github.com/minecraft-linux will have full access to the patches, everyone else only a mcpelauncher mod in binary form with an integrated license check (stripped debugging symbols). The launcher will continue to work without this mod, but is limited to Minecraft 1.17.30.

**Comment by ChristopherHX** [comment]
Done 1.19.60 beta is working
