### ISSUE TITLE
Texture bug ( with non dedicated graphic card )

### ISSUE THREAD

**Issue by BlckqFlorian** [minecraft-linux/mcpelauncher-manifest#601]
![Bildschirmfoto von 2021-09-07 18-14-39](https://user-images.githubusercontent.com/38558911/132377950-c3cdec07-4854-4817-93ea-0716e7f5d5f0.png)

**Comment by BlckqFlorian** [comment]
btw i use Nvidia GT 1030

**Comment by ChristopherHX** [comment]
Hmm, you found a bug in the Launcher UI.
I have written a texture mod for intel devices, you only need to enable it until the bug is fixed.
- Press the pencil icon (between the profile name and the big green button)
  - To edit your profile
- Change "Texture Patch" to Auto

_Mojang broke the game in 1.16.210!_

**Comment by BlckqFlorian** [comment]
okay, thank you!
