### ISSUE TITLE
Its not an issue but its something different

### ISSUE THREAD

**Issue by UnknownBinary009** [minecraft-linux/mcpelauncher-manifest#614]
Hi
i have an very old minecraft version its called 1.2.1.1 and if try to import it, it says that i need an apk for x86_64 and this apk is a armv7 apk but how can i force extract it because i've searched to get the x86_64 apk but i couldn't get any

**Comment by ChristopherHX** [comment]
Do not pirate apks of Minecraft, if you own it use the launcher to download them.

The launcher downloads 1.12 for you, but you need to use the AppImage or the macOS dmg file.
- The flatpak version has no 32 bit support and won't be able to open it
- If your mac has macOS 10.15 or higher, you cannot launch 1.12 either, due to removal of 32bit support from the OS.

**Comment by UnknownBinary009** [comment]
Ok thanks 👍
