### ISSUE TITLE
Cant open

### ISSUE THREAD

**Issue by LonIsHere** [minecraft-linux/mcpelauncher-manifest#617]
https://user-images.githubusercontent.com/91846826/135767591-438e4cfb-ab05-4c92-a537-9f949d724bf7.mp4
so when i try opening it with an apk, it wont work. It only works on a certain beta version of 1.14.
do I need to open it with a google account that I have bought minecraft with to work? I have an account where I bought it, so do I use that? Please reply!

**Comment by ChristopherHX** [comment]
> do I need to open it with a google account that I have bought minecraft with to work

Yes and I guess you pirated 1.14 apks, which is illegal.
**Piracy is a big problem for this launcher** and you are using an old version, new versions of this Launcher completly refuse to work without owning the game. The launcher told you there is an update available (blue banner), with all updates applied Minecraft 1.17.30 is working.

I'm closing this, because the launcher version you are using is out of support and arm apks will never work on your intel device.
