### ISSUE TITLE
GPL License Violation

### ISSUE THREAD

**Issue by andrewathalye** [minecraft-linux/mcpelauncher-manifest#637]
**Describe the bug**
The GPL License of certain components appears to be violated by including proprietary extensions.

**To Reproduce**
1. Start the launcher
2. Check "enable proprietary launcher extensions"
3. Observe that no additional files are downloaded, and note the lack of a separate executable for these extensions.

**Expected behavior**
Proprietary extensions should be included as separate executables in order to ensure that the GPL is respected. 

**Screenshots**
N/A

**Desktop (please complete the following information):**
- Linux (Gentoo)
- NVIDIA GPU / Wayland GBM
- AppImage v0.3.0-678 (ChristopherHX)

**Additional context**
This bug report constitutes a request for the source code of the launcher extensions under the terms of the GPL. Alternatively the incompatible version could be removed and replaced with one not containing proprietary code. It is possible that this has already been addressed, but a quick strace during the initial setup did not list any recognisable external executables.

EDIT: Revised phrasing to better reflect what was observed with strace. Apologies if this report causes any inconvenience, it just seemed important to me to ensure that the GPL was being properly applied here.

**Comment by ChristopherHX** [comment]
I complain about piracy and this **was** the only viably alternative **for me** to prevent piracy other than dicontinueing this project. 

 > Proprietary extensions should be included as separate executables in order to ensure that the GPL is respected.

They are seperate independend android shared libaries .so files. I don't think this violates anything. Delay download is to time intensive to implement for me.

See
https://github.com/ChristopherHX/mcpelauncher-manifest/issues/48#issuecomment-962518143

Source code of the extension
https://github.com/minecraft-linux/mcpelauncher-updates
I grant you also the GPL license for this repository if the MIT license doesn't fit.

Do what ever you want with it, it is public since ca. 7 days after release.

_I discontinued maintaining this project, published the extension and removed the integration of the extension_

**Comment by andrewathalye** [comment]
I understand. Apologies for all of the trouble, I merely wasn't sure from my side whether the GPL license could still be applied. Best of luck in all you do.

**Comment by noneistaken** [comment]
Compile https://gitlab.com/mcpelauncher/mcpelauncher and https://gitlab.com/mcpelauncher/mcpelauncherhttps://gitlab.com/mcpelauncher/mcpelauncher and call it a day
