### ISSUE TITLE
Flatpak fails to launch: Unable to find target for this triple (no targets are registered)

### ISSUE THREAD

**Issue by benthetechguy** [minecraft-linux/mcpelauncher-manifest#638]
**Describe the bug**
When I try to run the launcher, the window pops up for a split second and disappears as the application crashes.

**To Reproduce**
1. Run `flatpak run io.mrarm.mcpelauncher`
2. See window pop up and instantly close with nothing but two errors and a warning in the console (see below).

**Expected behavior**
I expected the launcher to start like it's supposed to.

**Screenshots**
Console output:
```
libEGL warning: DRI2: failed to authenticate
Qt: Session management error: Authentication Rejected, reason : None of the authentication protocols specified are supported and host-based authentication failed
Unable to find target for this triple (no targets are registered)
```

**Desktop (please complete the following information):**
 - OS: Debian 11 GNU/Linux (armhf)
 - Version: Can't see the full version name since the program won't launch, `flatpak info` tells me v0.2.3.
 - Installation Type: Flatpak

**Additional context**
This is a Samsung Chromebook XE303C12 that I have installed Debian on. There's nothing special about the Debian installation other than its architecture of armhf, so I don't see that being much of a problem, but I thought it was worth mentioning. I got the AppImage version to run, but I couldn't get it to load the Google login page, and there were many more errors, about some libraries like libselinux and others.

**Comment by ChristopherHX** [comment]
flatpak armhf is no longer supported, because armhf has been removed from the used flatpak sdk.

See https://github.com/flathub/io.mrarm.mcpelauncher/issues/54#issuecomment-902854369

Minecraft 1.17.40+ requires launcher version v0.3.0, the armhf flatpak has stopped receiving updates since v0.2.3.

For the appimage it might be due debian 11 armhf:
If you see this: https://discord.com/channels/429580677617418240/515450871664869397/908746647012532245
try this
```
QTWEBENGINE_CHROMIUM_FLAGS=--disable-seccomp-filter-sandbox ./file.AppImage
```

Source https://forum.vivaldi.net/topic/53399/crashing-seccomp-bpf-failure-in-syscall-0403-rpi4-8gb-ubuntu20-10-arm64-armhf/4

**Comment by benthetechguy** [comment]
Thanks, the appimage started working when I added that flag.
