### ISSUE TITLE
Launcher is acting like I'm not signed in (Google Authentication Issue?)

### ISSUE THREAD

**Issue by OCsonic** [minecraft-linux/mcpelauncher-manifest#670]
I've attempted to log in multple times and restarted the program multiple times, but upon signing in I am always met with a play button that says "Please Wait...", If I edit the version profile to try to select a version it shows a no selectable versions (I also tried with unverified and incompatiable versions checked), Lastly when I go into the versions menu under the launcher settings it says "(you must own the game)" after Import.apk. This all leads me to believe that there is some sort of authentication issue.

![image](https://user-images.githubusercontent.com/50123826/157636248-b3ca5d9f-8c3c-462c-983d-6b05a7c6866b.png)

 - OS: Linux (Suite66 Init incase it makes any difference)
 - Version: Latest on AUR
 - Installation Type: AUR

**Comment by ChristopherHX** [comment]
Please provide the output of the troubleshooter window, you find it in settings page where you can sign in / out and so on.

That you still see `Please wait...` means there must be connection errors ( via libuv / libcurl ) to google play services after the webview login, which are not detected by this application. Otherwise it should switch within a **few seconds** to `1.18.12` or `"You must own the game"`.

- Proxy?
- Restrictions of your Internet Service Provider?

Can you reproduce it with the AppImage https://github.com/ChristopherHX/linux-packaging-scripts/releases/latest?
If the first is yes then => Can you reproduce it on an ubuntu 20.04 VM with the AppImage?

_I'm not currently not working on this Project, please don't expect anything in the coming months._

**Comment by OCsonic** [comment]
![image](https://user-images.githubusercontent.com/50123826/157755156-bf521196-818b-4007-a5ae-ce8fe5d3c2ef.png)
This is the output of the troubleshooter window, Also I tried the appimage and it instantly worked.

**Comment by OCsonic** [comment]
Update : I fixed the issue by using libcurl-compat

**Comment by oeramo** [comment]
@OCsonic Did you mean that you just installed `libcurl-compat` on top of `curl` in your system and then everything just started working?

I am facing the same issue that you also had, everything is as you described. Relogged in / reset / reinstalled multiple times, before and after adding `libcurl-compat`. OS is Arch, `mcpelauncher` installed from the AUR. My versions of some of the packages that I seem to understand would be relevant to this issue:

```
curl 7.82.0-1
libcurl-compat 7.82.0-1
lib32-curl 7.82.0-1
libuv 1.43.0-1
openssl 1.1.1.n-1
mcpelauncher-linux-git v0.3.2.r0.g1da5aa2-1
mcpelauncher-msa-ui-qt-git v0.1.beta.2.r10.ge830ebe-1
mcpelauncher-msa-git v0.1.beta.2.r10.ge830ebe-1
mcpelauncher-ui-git v0.3.2.r0.g6039645-1
```

What should I do next?
