### ISSUE TITLE
Connection timeout when trying to connect to LAN games

### ISSUE THREAD

**Issue by hgabreu** [minecraft-linux/mcpelauncher-manifest#747]
**Describe the bug**
Can't connect to any multiplayer game. The games are shown on the friends list (same LAN), but when clicked to join, it times out after a while (around a minute) with a "Connection timed out. Unable to connect to world." message.

It's on the same LAN, running the same version: 1.19.51.01

**To Reproduce**
1. mcpelauncher-ui-qt -v [mcpelauncher-ui-qt.logs.txt](https://github.com/minecraft-linux/mcpelauncher-manifest/files/10333957/mcpelauncher-ui-qt.logs.txt)
2. Load load 1.19.51.01 and wait for the microsoft login to do its thing.
3. Click Play, then the Friends tab, try a LAN game running the same bedrock version.
4. After a while on the "Connecting to multiplayer game", it gives up with the error: "Connection timed out. Unable to connect to world." 

**Expected behavior**
I expected to log into the game normally.

**Screenshots**
[mcpelauncher-client.logs.txt](https://github.com/minecraft-linux/mcpelauncher-manifest/files/10333956/mcpelauncher-client.logs.txt)

**Desktop (please complete the following information):**
 - OS: Archlinux 6.1.1-arch1-1
 - Version:
mcpelauncher-linux-git v0.5.0.r3.g68ac253-1
mcpelauncher-msa-ui-qt-git v0.3.4.r1.g41138a9-1
mcpelauncher-ui-git v0.3.2.r6.g485df2e-1

 - Installation Type: built from AUR package builds

**Additional context**
Unfortunately it's quite hard to rollback my android versions on my phone to test this with previous bedrock versions. But I had LAN games working fine yesterday with version 1.19.41.01 and previous release of ng branch.
Local worlds work fine, it's just multiplayer that is failing.
I also tried removing my ~/.local/share/mcpelauncher but got the same issue.

**Comment by Lunakin42** [comment]
Just wanted to add I'm having the same issue. I'm running Fedora 35 KDE using the FlatPak launcher.
I can connect to my local server with my phone and windoze PC without issue. But using this launcher it just sits at connecting, and then eventually times out.

**Comment by fragmuffin** [comment]
+1; me too, same symptoms

Minecraft Version: `1.19.51.01 (X86_64)`

<details><summary>System Details</summary>

```bash
$ uname -orm
5.15.0-56-generic x86_64 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy

```
</details>
<details><summary>Flatpak Details</summary>

```
$ flatpak --version
Flatpak 1.12.7

$ flatpak list
Name                                 Application ID                               Version          Branch          Installation
Minecraft Bedrock Launcher           io.mrarm.mcpelauncher                        v0.6.0           stable          system
Mesa                                 org.freedesktop.Platform.GL.default          21.3.9           21.08           system
openh264                             org.freedesktop.Platform.openh264            2.1.0            2.0             system
Adwaita theme                        org.kde.KStyle.Adwaita                                        6.3             system
KDE Application Platform             org.kde.Platform                                              6.3             system
```

</details>

# Changes over time...

Changes to login, and authorised access appears to change in strange ways when left for long periods.

## Case 1) ~30min

1) Open app, and allow it to login (avatar was incorrect :no_entry:, but username was correct :heavy_check_mark: )
2) After ~8min, avatar is replaced with loading animation.

<img src="https://user-images.githubusercontent.com/2626190/210508022-3031d6ab-5f04-4a62-8818-ef4cf8fac90a.png" width="30%" /> &nbsp; <img src="https://user-images.githubusercontent.com/2626190/210509155-08056ee8-39f3-4f13-8166-ce7f6b9c3326.png" width="30%" />

3) after 30min `Fetching Realms...` changes from blank, to loading animation

<img src="https://user-images.githubusercontent.com/2626190/210537542-3c95e0d2-c7fe-44ca-8b46-76687fd6401a.png" width="30%" /> &nbsp; <img src="https://user-images.githubusercontent.com/2626190/210512904-0d993e3a-033c-4e95-a4c6-9ebd16ccb2c8.png" width="30%" />

However, in this case, nothing changed after this time... no servers could be joined.
Although I didn't wait for...

## Case 2) ~2hrs

1) I opened Minecraft.... and clicked nothing for ~2hrs (forgot about it TBH).
2) Clicked `[Play]`, and my realms (or lack thereof) was detected... progress

<img src="https://user-images.githubusercontent.com/2626190/210512904-0d993e3a-033c-4e95-a4c6-9ebd16ccb2c8.png" width="30%" /> &nbsp; <img src="https://user-images.githubusercontent.com/2626190/210535207-00aa8e92-db7e-48f6-9bed-0fcbc7552787.png" width="30%" />

3) Clicked on `[Friends]`, _Joinable Realms_ is visible (instead of blank).

<img src="https://user-images.githubusercontent.com/2626190/210535962-62930298-5dc0-454f-bf05-07804ee6a475.png" width="30%" />

and finally...

4) Clicked on my local server

<img src="https://user-images.githubusercontent.com/2626190/210536443-0d1f611a-35d1-416e-b76c-0ebe36e3209d.png" width="30%" /> &nbsp; <img src="https://user-images.githubusercontent.com/2626190/210536530-db679507-abe5-4358-b4ad-cb521815a3a9.png" width="30%" />

**:heavy_check_mark: SUCCESS**

5) Quitting, and joining again, works as well.

Joining the local server both times takes much longer than I expect, ~10sec until it's "Loading Resources".
My phone is much faster.

I understand this is quite clumsy debugging on my part... but I hope this is useful in some way.
Please let me know if you'd like any other information.

---

_edit_: It may also be worth noting that URLs don't open from the launched app, details in flathub/io.mrarm.mcpelauncher#90 . Which means I cannot login using to my Microsoft account using `v1.19.51`, instead I logged in using `v1.19.40`, then opened `v1.19.51` which logged in automatically.

**Comment by are27** [comment]
Same issue with v1.19.51

What doesn't work:
Connecting to a LAN server
Connecting to a friend's game (a world created on their device)

What does work:
Friend connecting into a world I've created locally on my device

Older versions used to connect to the server fine

**Comment by ChristopherHX** [comment]
Do you notice any difference in [v0.7.0](https://github.com/minecraft-linux/mcpelauncher-manifest/releases/tag/v0.7.0)? _This version won't be released as binary due to known issues, you can get a snapshot here https://github.com/minecraft-linux/mcpelauncher-manifest/actions/runs/3867378333_

I made the xbox live http client async non blocking, previously it has been implemented as a simple blocking method.

- The xbox live login button now responds much faster if you press login
- The external server list loads much faster
- The Achivements are no longer timeout if you open them for the first time after loading the game

I don't think this fixes timeouts while joining servers.

**Comment by fragmuffin** [comment]
Yes!, that's fixed it for me!

Tested `x86_64-v0.6.0.9` (from the above _snapshot_ link)... not sure about the v6 label... but it's definitely more recent than the last `.AppImage` I tried.

## LAN Connection :heavy_check_mark: 

Using saved session data, connecting to local server works :tada: 

## WAN Connection :heavy_check_mark: 

Same auth as above, connecting to some random remote server works :tada: 

## Logout / Login :heavy_check_mark: 

Logging out and logging works....
Then with new login, repeating the above LAN & WAN tests also work

Nice work @ChristopherHX :grin: , thank you.

**Comment by hgabreu** [comment]
It took me a while to get the new version working here, but I can confirm it fixed the issue indeed. Thank you
