### ISSUE TITLE
Mouse losing focus constantly since newest update

### ISSUE THREAD

**Issue by omginput** [minecraft-linux/mcpelauncher-manifest#786]
**Describe the bug**
Since the newest update the mouse loses focus so one can see it and operate in OS but not in game. One has to press ESC 2 times to get the focus back. This happens in an interval of about 1 minute.

**To Reproduce**
1. Hop on a server and play

**Expected behavior**
Mouse keeps focus ingame

**Desktop (please complete the following information):**
 - OS: Fedora 37
 - Version Flatpak 0.8.1
 - Installation Type Flatpak

**Comment by ChristopherHX** [comment]
I'm not affected by any `mouse "unlock" issue` on ubuntu 22.04.

- Do you have any device connected, which claims to be a joystick (can be a gamepad, mouse (I'm not joking, had to revert auto gamepad detection due to that) and keyboard)?
- Does your mouse unlock if you don't press any key or mouse for 2 seconds and then move your mouse?
- Are you shure it is 1 second? I mean 2 seconds are required to switch from mouse input mode to gamepad
  - For a gamepad to switch you would have to either press a button or move an analog stick
  - For mouse to switch from gamepad in mouse mode takes 0s and will always unlock the mouse, unless you can tell me how reliable know when the mouse should be visible or not. The problem is if you open settings, menu and inventory you would be distracted if you cannot find your mouse cursor.


The last time I changed the above logic was in fall 2021, thats long time ago and now there are issues with it?

- Are you using mouse, because gamepad input doesn't work in 1.19.60? Under 1.19.5X and below gamepad input is still working

**Comment by ChristopherHX** [comment]
Fixed version 0.8.5 (second build)
