### ISSUE TITLE
mcpelauncher dnf package conflict with telegram

### ISSUE THREAD

**Issue by falentio** [minecraft-linux/mcpelauncher-manifest#840]
1.20 version support

**Comment by ChristopherHX** [comment]
Do you have a problem with updating this launcher to v0.10.0?

Do you have a problem with using 1.20.0 with launcher release v0.10.0?

I ask because a 1.20 compatibility update has been released last Wednesday, shortly after beeing published by Mojang.

**Comment by falentio** [comment]
oh sorry, I did not know the launcher update, I was insttalled yesterday but somehow I got v0.9, I install v0.10.0 now

**Comment by falentio** [comment]
![image](https://github.com/minecraft-linux/mcpelauncher-manifest/assets/75155697/9fe9cfb4-e1ed-4f20-b924-635b82f9b1f0)

it looks like mcpelauncher conflicting with telegram, because whenever I install telegram, it also downgrading mcpe launcher

**Comment by ChristopherHX** [comment]
> Skipping packages with broken dependencies:
  telegram-desktop 4.8.1

Sounds like a telegram-desktop issue and then some dnf magic downgrades this app.

- You can also install a launcher mod to be able to open 1.20 in v0.9.x without updating see here: https://github.com/minecraft-linux/mcpelauncher-client/issues/66#issuecomment-1563349236
- Install the AppImage (no package manager)
- Install the Flatpak (different package manager, will never downgrade due to broken packages)
