### ISSUE TITLE
Render Dragon shaders for mac

### ISSUE THREAD

**Issue by jrapf32** [minecraft-linux/mcpelauncher-manifest#937]
**Is your feature request related to a problem? Please describe.**
I can't add Render Dragon shaders PBR error.
**Describe the solution you'd like**
Add support.

**Comment by ChristopherHX** [comment]
Are you on linux with OpenGL ES 3.1+ Graphics support?

I mean pbr based shaders were working months ago on a nintendo switch using this launcher on ubuntu 18.04.

**Comment by jrapf32** [comment]
I'm on a mac. It gives a warning symbol that pbr is not supported.

**Comment by jrapf32** [comment]
<img width="341" alt="Screenshot 2024-01-24 at 4 18 00 PM" src="https://github.com/minecraft-linux/mcpelauncher-manifest/assets/30359766/374663ed-d7cf-4efa-a12e-ef7a82e19c87">

**Comment by ChristopherHX** [comment]
Yes it won't work on macOS, because we are unable to get OpenGL ES 3.1 emulated on them.

We use https://github.com/google/angle to get OpenGL ES 3.0 on macOS.

Apple decided to deprecate the OpenGL Framework even before official deprecation and lacks features used by angle to emulate OpenGL ES 3.1. Therefore is Metal emulation the only possible way, but that backend doesn't have OpenGL ES 3.1 support implemented yet.

I'm waiting for an external dependency here, the angle readme mentioned they have plans for OpenGL ES 3.2 without timelines. Could take years.

**Comment by jrapf32** [comment]
Closing as it would take years for this feature request to get implemented.
