### ISSUE TITLE
option to let you launch unsupported versions

### ISSUE THREAD

**Issue by Spike1377** [minecraft-linux/mcpelauncher-manifest#964]
it should let you start the game, even if its unsupported

even if its not a beta version it still dosnt let you start it. it lets you download it but not start it, stupid

https://github.com/minecraft-linux/mcpelauncher-manifest/assets/113913612/a356c89b-8187-4484-9fc6-c492ec6318bf

**Comment by ChristopherHX** [comment]
You need to update mcpelauncher-client to v0.14.0+, in your video there is v0.13.0 that cannot load that specfic game version to memory.

> option to let you launch unsupported versions

You found it by unblocking downloading that new game versions via old launchers, but it's not a solution for every update of the game

> it lets you download it but not start it, stupid

You get that popup if mcpelauncher-client is unable to dlopen libminecraftpe.so, which is a fatal failure where it doesn't make sense to see a crash window

_Are you able to suggest how to improve the error message to make it more clear that the launcher tried it's best and failed badly?_

**I noticed via your issue that the apt and rpm repo had an release publish failure, which is fixed by now, so please try to update**, the nightly releases are available if there is no new regular release

**Comment by ChristopherHX** [comment]
I see that you need to run

`flatpak update`

to get the update, the flatpak app has no permission for doing updates
