### ISSUE TITLE
Allow installation of ChromeOS builds if owned by the user's Google account

### ISSUE THREAD

**Issue by OpenSauce04** [minecraft-linux/mcpelauncher-manifest#980]
**Is your feature request related to a problem? Please describe.**
This request is related to the sprint strafing issue which has been present since 1.19.50

**Describe the solution you'd like**
As a workaround to [MCPE-170810](https://bugs.mojang.com/browse/MCPE-170810), would it be possible to add a setting which pulls the APK file for the ChromeOS build of the game if the currently signed in Google Play account owns it? The issue reportedly does not exist on ChromeOS, despite simply being a modified version of the Android port.

This would greatly help to overcome this incredibly annoying issue in the meantime while we wait for Mojang to (hopefully) fix it themselves, although I don't have my hopes up given that it has been present for about a year and a half.

**Describe alternatives you've considered**
N/A

**Comment by ChristopherHX** [comment]
I actually have no idea how to download Chrome OS versions via the play api client used by the launcher.

**I didn't buy that version of the game and are not eligible to download it**

What playstore identifier is the chromeos version using?

- `com.mojang.minecraftpe` Android
- `com.mojang.minecrafttrialpe` I think that was Android Trial
- `com.mojang.minecraftedu` Android Education

If it's different I might be able to provide you something to test if you can download it, since other non chromeos android games download just fine with a search and replace

There are almost zero info about the chromeos version if no chromeos device has ever been used.

Playstore only writes "sold seperately"

**Comment by OpenSauce04** [comment]
I do not currently have access to the ChromeOS version either, and was partially making this issue to prod on whether you had any knowledge of it either
Over the last couple of days, I have attempted to do a little research myself, and as you mentioned there is almost no information online about it. I would be willing to put in the like £13 required to get the ChromeOS version of the game and do some research on my own though. I will not be able to do this currently, as my life is very busy.

**Comment by ChristopherHX** [comment]
- You can start with trying getting something like fydeos.io running
- Enable adb
- Install The minecraft trial
- Try if the strafe sprinting works there
- try extracting it

I assume chromeos trial is already different on chromeos.

If the trial works then you can try it on the launcher before actually purchasing the upgrade.

**Comment by ChristopherHX** [comment]
> as my life is very busy

Me too, I'm just ignoring the bug and move on. Nothing easier than that.

**Comment by OpenSauce04** [comment]
I will attempt to implement this feature at a later date as a pull request

**Comment by OpenSauce04** [comment]
Bought the ChromeOS version of Minecraft and tried the new ChromeOS Mode option, and it works like a dream. Thank you for your work!
